### ISSUE TITLE
TODO Sepetember

### ISSUE THREAD

**Issue by thelamer** [linuxserver/docker-jenkins-builder#31]
We need to implement some options for job pruning: 
https://support.cloudbees.com/hc/en-us/articles/115000237071-How-do-I-set-discard-old-builds-for-a-Multi-Branch-Pipeline-Job
Also might want to grab some other options like `parallelsAlwaysFailFast`
https://jenkins.io/doc/book/pipeline/syntax/#options

This month will also see the introduction of templated issue and pull request templates bring the total templated files to 5, we should modify the logic to accept an array of files instead of seperate md5 comparisons and ifs for each of them to support even further templating.

**Comment by j0nnymoe** [comment]
For the issure and pull request templates, we need to choose which one from here: https://github.com/stevemao/github-issue-templates suits our project best.

**Comment by thelamer** [comment]
Reference and closing https://github.com/linuxserver/docker-jenkins-builder/pull/32
