### ISSUE TITLE
Swap Readme Language and cutover from Dockerhub

### ISSUE THREAD

**Issue by thelamer** [linuxserver/docker-jenkins-builder#68]
We need to form a game plan for this monthly Nov 2nd the pull rate limits go into effect for Dockerhub. 
I think Github makes the most sense for default commands in the readmes as it is basically our home base.

On top of language we need to update the cache for the arm builds that is pushed off from the builders. 

That is what applies to this repo, but we need to redo all of our dockerfiles, I can adapt https://github.com/linuxserver/alpiner to script this to create branches for all our projects to use the new baseimage endpoints. 

This issue is for general discussion surrounding this, but I will proceed on the backend with this gameplan.

**Comment by thelamer** [comment]
Ref branch https://github.com/linuxserver/docker-jenkins-builder/tree/monthly-github

**Comment by thelamer** [comment]
Ref baseimage changes to support GHCR mods: 
https://github.com/linuxserver/docker-baseimage-alpine/pull/58
https://github.com/linuxserver/docker-baseimage-ubuntu/pull/54
https://github.com/linuxserver/docker-baseimage-ubuntu/pull/53

Overlay updates also needed for monthly: 
https://github.com/linuxserver/docker-baseimage-ubuntu/pull/51
https://github.com/linuxserver/docker-baseimage-ubuntu/pull/50
https://github.com/linuxserver/docker-baseimage-alpine/pull/57

**Comment by Roxedus** [comment]
We also need to switch the place we pull our helpers and buildcaches from, as we would be be rate-limited on more or less the 8th pipeline build in the span of 6 hours.

To list a few places:
https://github.com/linuxserver/docker-jenkins-builder/blob/monthly-github/roles/generate-jenkins/templates/Jenkinsfile.j2#L368
https://github.com/linuxserver/docker-jenkins-builder/blob/monthly-github/roles/generate-jenkins/templates/Jenkinsfile.j2#L669

I think this also to some extent counts where we now use the IMAGE variable.
