### ISSUE TITLE
Cleanup images on Arm hosts - Next monthly

### ISSUE THREAD

**Issue by thelamer** [linuxserver/docker-jenkins-builder#71]
https://github.com/linuxserver/docker-jenkins-builder/blob/master/roles/generate-jenkins/templates/Jenkinsfile.j2#L518 we need to purge the version tag on the arm builders to keep them clean.

**Comment by aptalca** [comment]
x86_64, too
https://github.com/linuxserver/docker-jenkins-builder/blob/master/roles/generate-jenkins/templates/Jenkinsfile.j2#L793-L798
we need to add `${DELETEIMAGE}:amd64-${EXT_RELEASE_TAG}` and such

**Comment by aptalca** [comment]
Fixed in #82
