### ISSUE TITLE
Parameters section in README uses incorrect volume syntax

### ISSUE THREAD

**Issue by AGSPhoenix** [linuxserver/docker-jenkins-builder#91]
The README template shows volume usage incorrectly in the parameters section, leaving out the host path. This may confuse users who aren't already familiar with Docker's volume syntax.

This example fix copies the syntax from the CLI example to the parameters section: https://github.com/AGSPhoenix/docker-jenkins-builder/commit/7e1eec267f88586bf7599f9e390b3b83a822bd94. Further clarification with <>s around items that need to be replaced (as done on [the LS.io docs site](https://docs.linuxserver.io/general/swag#creating-a-swag-container)) would also be helpful, but I'm not familiar enough with your repos to know if that change should be made globally.

Earlier issues mention batching changes together, and this certainly doesn't seem like an important enough change to spend buildserver time on for the dozens of repos that use volumes, so I've skipped submitting a PR for now.

**Comment by AGSPhoenix** [comment]
Bump.

**Comment by nemchik** [comment]
It looks like you've done the work. I'll have a look tomorrow and pull your commit in. Thanks!

**Comment by nemchik** [comment]
I discussed this internally with the team and we don't feel that this change is necessary. The table of information it affects is describing the examples for the docker run and docker compose above the table, and those are meant to be the examples to use, not the description table. The examples are as complete as we can make them, with the only thing needing to change being the storage locations for the host side of the volumes.

Thanks again for putting thought into this.
